version: '2'

services:
  lear-app:
    image: php:7.4-fpm-alpine
    volumes:
      - ./:/var/www/html
    links:
      - app

  lear-nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./:/var/www/html
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

networks:
  default:
    external:
      name: dev